"""empty message

Revision ID: f604de78b7bf
Revises: 6ee356d3e910
Create Date: 2022-03-15 19:33:10.632733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f604de78b7bf'
down_revision = '6ee356d3e910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_basic', sa.Column('Administrator', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_basic', 'Administrator')
    # ### end Alembic commands ###
